version: '3'

services:
  prometheus-exporter:
    build: .
    ports:
      - "${PORT:-9584}:9584"
    environment:
      - PORT=${PORT:-9584}
      - SERVER_NAME_FILTER=${SERVER_NAME_FILTER:-[^b🐟 CaRP^r Test Server]}
    depends_on:
      - promtail
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /app/log:/app/log/
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    ports:
      - "9080:80"  # Expose Promtail's logs on port 9080
