clients:
  - url: http://192.168.1.77:3100/loki/api/v1/push
    external_labels:
      job: beammp_exporter

scrape_configs:
  - job_name: beammp_exporter
    static_configs:
      - targets:
          - localhost
        labels:
          job: beammp_exporter
          __path__: /var/log/beammp/*.log
